# Generated by Django 2.2.24 on 2021-09-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Kart Fotoğrafı Ekleyin: ')),
                ('title', models.CharField(max_length=50, verbose_name='Kart Başlığı: ')),
                ('content', models.TextField(max_length=220, verbose_name='İçerik')),
                ('location', models.CharField(max_length=100, verbose_name='Lokasyon')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
