# Generated by Django 2.2.24 on 2021-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Kart Fotoğrafı Ekleyin: '),
        ),
    ]
