# Generated by Django 2.2.24 on 2021-09-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20210920_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=200, verbose_name='Soy İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('age', models.CharField(max_length=30, verbose_name='Yaş')),
                ('education', models.CharField(choices=[('', 'Seçiniz...'), ('Lise', 'Lise'), ('Üniversite', 'Üniversite'), ('Yüksek Lisans', 'Yüksek Lisans')], max_length=80, verbose_name='Eğitim Seviyesi')),
                ('status', models.CharField(choices=[('', 'Seçiniz...'), ('Stajyer', 'Stajyer'), ('Tecrübesiz', 'Tecrübesiz'), ('Orta Tecrübeli', 'Orta Tecrübeli'), ('Tecrübeli', 'Tecrübeli')], default='Bilinmiyor', max_length=200, verbose_name='Statü')),
                ('department', models.CharField(choices=[('', 'Seçiniz...'), ('Yazılım', 'Yazılım'), ('Halkla İlişkiler', 'Halkla İlişkiler'), ('Stajyer', 'Stajyer'), ('Web Tasarım', 'Web Tasarım'), ('Tasarımcı', 'Tasarımcı')], default='Bilinmiyor', max_length=200, verbose_name='Departman')),
                ('about', models.TextField(verbose_name='Hakkınızda')),
                ('appeal_date', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('cv', models.FileField(blank=True, null=True, upload_to='CVs', verbose_name='CV Ekleyin: ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='company.Company')),
            ],
        ),
    ]
